CREATE TABLE MASTER (
  USERID VARCHAR(20),
  NAME VARCHAR(255),
  ROLLNO VARCHAR(6),
  PRIMARY KEY(USERID, ROLLNO)
);

CREATE TABLE ATTENDANCE (
  USERID VARCHAR(10),
  DATE_ VARCHAR(20),
  IN_TIME VARCHAR(20),
  OUT_TIME VARCHAR(20),
  PRIMARY KEY(USERID, DATE_, IN_TIME, OUT_TIME)
);

CREATE TABLE BLOCKING (
  ACADEMIC_YEAR VARCHAR(12),
  SEMESTER VARCHAR(5),
  LAB VARCHAR(6),
  _DAY VARCHAR(10),
  FROMPERIOD INTEGER,
  TOPERIOD INTEGER,
  PRIMARY KEY(ACADEMIC_YEAR, SEMESTER, LAB, _DAY, FROMPERIOD, TOPERIOD)
);

CREATE TABLE BOOKING (
  STAFFID VARCHAR(6),
  PROGRAMME VARCHAR(10),
  _YEAR INTEGER,
  LAB VARCHAR(6),
  BOOKINGDATE DATE,
  ENTRYDATE DATE,
  FROMPERIOD INTEGER,
  TOPERIOD INTEGER,
  PURPOSE VARCHAR(1000),
  PRIMARY KEY( LAB, BOOKINGDATE, FROMPERIOD, TOPERIOD )
);

CREATE TABLE COMPLAINTS (
  COMPLAINTID INT NOT NULL AUTO_INCREMENT,
  USERID VARCHAR(6),
  LAB VARCHAR(6),
  _ROW INTEGER,
  _COL INTEGER,
  SYSTEMNO INTEGER,
  REQUIREMENT VARCHAR(1000),
  DATE_TIME DATETIME,
  _STATUS VARCHAR(20),
  RESOLVEDDATE DATE,
  REMARKS VARCHAR(500),
  RESOLVEDBY VARCHAR(40),
  PRIMARY KEY(COMPLAINTID)
);

CREATE TABLE COURSE_DATES (
  ACADEMIC_YEAR VARCHAR(12),
  CLASS VARCHAR(10),
  SEMESTER VARCHAR(5),
  START_DATE DATE,
  END_DATE DATE,
  PRIMARY KEY (ACADEMIC_YEAR, CLASS, SEMESTER)
);

CREATE TABLE LOGIN_REQUESTS (
  REQUESTID INT NOT NULL AUTO_INCREMENT,
  STAFFID VARCHAR(6),
  STAFFNAME VARCHAR(40),
  STAFFEMAIL VARCHAR(80),
  CLASS VARCHAR(5),
  DATEREQUESTED DATETIME,
  DATENEEDED DATE,
  FROMPERIOD INTEGER,
  TOPERIOD INTEGER,
  _TYPE VARCHAR(10),
  NOOFLOGINS INTEGER,
  TOOLS VARCHAR(40),
  SERIES VARCHAR(20),
  _STATUS VARCHAR(20),
  PRIMARY KEY(REQUESTID)
);

CREATE TABLE SCHEDULE (
  ACADEMICYEAR VARCHAR(12),
  SEMESTER VARCHAR(5),
  _YEAR INTEGER,
  PROGRAMME VARCHAR(10),
  LAB VARCHAR(6),
  _DAY VARCHAR(10),
  PERIOD INTEGER,
  PRIMARY KEY(_DAY, LAB, PERIOD, ACADEMICYEAR, SEMESTER)
);

CREATE TABLE WIFI (
  ROLLNO VARCHAR(6),
  _NAME VARCHAR(50),
  MAC VARCHAR(20),
  MODEL VARCHAR(100),
  _TYPE VARCHAR(15),
  MOBILE VARCHAR(10),
  ROUTERNAME VARCHAR(20),
  VERIFY VARCHAR(20),
  _STATUS VARCHAR(10),
  PRIMARY KEY(ROLLNO)
);

CREATE TABLE `DEVICE_MASTER` (
  `MODEL` VARCHAR(50) DEFAULT NULL,
  `STATUS` VARCHAR(20) NOT NULL DEFAULT 'Working',
  `INVOICENO` VARCHAR(50) NOT NULL,
  `INVOICEDATE` VARCHAR(10) DEFAULT NULL,
  `LOCATION` VARCHAR(10) NOT NULL DEFAULT 'Store',
  `DEVICETYPE` VARCHAR(30) NOT NULL,
  `MAC` VARCHAR(20) DEFAULT NULL,
  `RAM` VARCHAR(8) DEFAULT NULL,
  `SERIALNO` VARCHAR(50) NOT NULL,
  `SPECIFICATION` VARCHAR(150) DEFAULT NULL,
  `VERIFY` VARCHAR(50) DEFAULT 'not verified',
  PRIMARY KEY (`SERIALNO`)
);

CREATE TABLE `DUMP` (
  `DUMPID` INT NOT NULL AUTO_INCREMENT,
  `DISPOSALDATE` VARCHAR(10) DEFAULT NULL,
  `VERIFY` VARCHAR(15) DEFAULT 'not verified',
  `SERIALNO` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`DUMPID`),
  UNIQUE KEY `UNIQUE_SERIALNO` (`SERIALNO`),
  KEY `SERIALNO` (`SERIALNO`),
  CONSTRAINT `DUMP_IBFK_1` FOREIGN KEY (`SERIALNO`) REFERENCES `DEVICE_MASTER`(`SERIALNO`)
);

CREATE TABLE `COMPUTER_MASTER` (
  `LOCATION` VARCHAR(10) NOT NULL,
  `MOUSESNO` VARCHAR(50) DEFAULT NULL,
  `KEYBOARDSNO` VARCHAR(50) DEFAULT NULL,
  `MONITORSNO` VARCHAR(50) DEFAULT NULL,
  `CPUSNO` VARCHAR(50) DEFAULT NULL,
  `SYSTEMNO` INT NOT NULL,
  KEY `MONITORSNO` (`MONITORSNO`),
  KEY `MOUSESNO` (`MOUSESNO`),
  KEY `KEYBOARDSNO` (`KEYBOARDSNO`),
  KEY `CPUSNO` (`CPUSNO`),
  CONSTRAINT `COMPUTER_MASTER_IBFK_1` FOREIGN KEY (`MONITORSNO`) REFERENCES `DEVICE_MASTER` (`SERIALNO`),
  CONSTRAINT `COMPUTER_MASTER_IBFK_2` FOREIGN KEY (`MOUSESNO`) REFERENCES `DEVICE_MASTER` (`SERIALNO`),
  CONSTRAINT `COMPUTER_MASTER_IBFK_3` FOREIGN KEY (`KEYBOARDSNO`) REFERENCES `DEVICE_MASTER` (`SERIALNO`),
  CONSTRAINT `COMPUTER_MASTER_IBFK_4` FOREIGN KEY (`CPUSNO`) REFERENCES `DEVICE_MASTER` (`SERIALNO`)
);

CREATE TABLE `DEVICE` (
  `DEVICETYPE` VARCHAR(20) DEFAULT NULL
);

CREATE TABLE `LOCATION` (
  `LAB` VARCHAR(20) DEFAULT NULL
);

SELECT
  DATE_FORMAT(DISPOSALDATE, '%d/%m/%Y') AS DISPOSALDATE_FORMATTED
FROM
  DUMP;

ALTER TABLE DUMP MODIFY DISPOSALDATE VARCHAR(10);

UPDATE DUMP
SET
  DISPOSALDATE = DATE_FORMAT(
    STR_TO_DATE(DISPOSALDATE, '%Y-%m-%d'),
    '%d/%m/%Y'
  );

SELECT
  DATE_FORMAT(INVOICEDATE, '%d/%m/%Y') AS INVOICEDATE_FORMATTED
FROM
  DEVICE_MASTER;

ALTER TABLE DEVICE_MASTER MODIFY INVOICEDATE VARCHAR(10);

UPDATE DEVICE_MASTER
SET
  INVOICEDATE = DATE_FORMAT(
    STR_TO_DATE(INVOICEDATE, '%Y-%m-%d'),
    '%d/%m/%Y'
  );